/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db.tables.records;


import com.casino.jooq.db.tables.Bets;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BetsRecord extends UpdatableRecordImpl<BetsRecord> implements Record7<Integer, Double, Timestamp, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 1588615391;

    /**
     * Setter for <code>casino.bets.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>casino.bets.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>casino.bets.amount</code>.
     */
    public void setAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>casino.bets.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>casino.bets.time</code>.
     */
    public void setTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>casino.bets.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>casino.bets.userId</code>.
     */
    public void setUserid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>casino.bets.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>casino.bets.gameId</code>.
     */
    public void setGameid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>casino.bets.gameId</code>.
     */
    public Integer getGameid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>casino.bets.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>casino.bets.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>casino.bets.number</code>.
     */
    public void setNumber(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>casino.bets.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Double, Timestamp, Integer, Integer, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Double, Timestamp, Integer, Integer, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Bets.BETS.ID;
    }

    @Override
    public Field<Double> field2() {
        return Bets.BETS.AMOUNT;
    }

    @Override
    public Field<Timestamp> field3() {
        return Bets.BETS.TIME;
    }

    @Override
    public Field<Integer> field4() {
        return Bets.BETS.USERID;
    }

    @Override
    public Field<Integer> field5() {
        return Bets.BETS.GAMEID;
    }

    @Override
    public Field<String> field6() {
        return Bets.BETS.STATUS;
    }

    @Override
    public Field<Integer> field7() {
        return Bets.BETS.NUMBER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Double component2() {
        return getAmount();
    }

    @Override
    public Timestamp component3() {
        return getTime();
    }

    @Override
    public Integer component4() {
        return getUserid();
    }

    @Override
    public Integer component5() {
        return getGameid();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public Integer component7() {
        return getNumber();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Double value2() {
        return getAmount();
    }

    @Override
    public Timestamp value3() {
        return getTime();
    }

    @Override
    public Integer value4() {
        return getUserid();
    }

    @Override
    public Integer value5() {
        return getGameid();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public Integer value7() {
        return getNumber();
    }

    @Override
    public BetsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BetsRecord value2(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public BetsRecord value3(Timestamp value) {
        setTime(value);
        return this;
    }

    @Override
    public BetsRecord value4(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public BetsRecord value5(Integer value) {
        setGameid(value);
        return this;
    }

    @Override
    public BetsRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public BetsRecord value7(Integer value) {
        setNumber(value);
        return this;
    }

    @Override
    public BetsRecord values(Integer value1, Double value2, Timestamp value3, Integer value4, Integer value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BetsRecord
     */
    public BetsRecord() {
        super(Bets.BETS);
    }

    /**
     * Create a detached, initialised BetsRecord
     */
    public BetsRecord(Integer id, Double amount, Timestamp time, Integer userid, Integer gameid, String status, Integer number) {
        super(Bets.BETS);

        set(0, id);
        set(1, amount);
        set(2, time);
        set(3, userid);
        set(4, gameid);
        set(5, status);
        set(6, number);
    }
}
