/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db.tables.records;


import com.casino.jooq.db.tables.Casinos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CasinosRecord extends UpdatableRecordImpl<CasinosRecord> implements Record3<Integer, String, Double> {

    private static final long serialVersionUID = -465249529;

    /**
     * Setter for <code>casino.casinos.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>casino.casinos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>casino.casinos.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>casino.casinos.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>casino.casinos.balance</code>.
     */
    public void setBalance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>casino.casinos.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Casinos.CASINOS.ID;
    }

    @Override
    public Field<String> field2() {
        return Casinos.CASINOS.NAME;
    }

    @Override
    public Field<Double> field3() {
        return Casinos.CASINOS.BALANCE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getBalance();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getBalance();
    }

    @Override
    public CasinosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CasinosRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CasinosRecord value3(Double value) {
        setBalance(value);
        return this;
    }

    @Override
    public CasinosRecord values(Integer value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CasinosRecord
     */
    public CasinosRecord() {
        super(Casinos.CASINOS);
    }

    /**
     * Create a detached, initialised CasinosRecord
     */
    public CasinosRecord(Integer id, String name, Double balance) {
        super(Casinos.CASINOS);

        set(0, id);
        set(1, name);
        set(2, balance);
    }
}
