/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db.tables.records;


import com.casino.jooq.db.tables.Dealers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DealersRecord extends UpdatableRecordImpl<DealersRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1721711881;

    /**
     * Setter for <code>casino.dealers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>casino.dealers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>casino.dealers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>casino.dealers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>casino.dealers.casinoId</code>.
     */
    public void setCasinoid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>casino.dealers.casinoId</code>.
     */
    public Integer getCasinoid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Dealers.DEALERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Dealers.DEALERS.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Dealers.DEALERS.CASINOID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCasinoid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCasinoid();
    }

    @Override
    public DealersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DealersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DealersRecord value3(Integer value) {
        setCasinoid(value);
        return this;
    }

    @Override
    public DealersRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DealersRecord
     */
    public DealersRecord() {
        super(Dealers.DEALERS);
    }

    /**
     * Create a detached, initialised DealersRecord
     */
    public DealersRecord(Integer id, String name, Integer casinoid) {
        super(Dealers.DEALERS);

        set(0, id);
        set(1, name);
        set(2, casinoid);
    }
}
