/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db.tables;


import com.casino.jooq.db.Casino;
import com.casino.jooq.db.Indexes;
import com.casino.jooq.db.Keys;
import com.casino.jooq.db.tables.records.CasinosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Casinos extends TableImpl<CasinosRecord> {

    private static final long serialVersionUID = 757461743;

    /**
     * The reference instance of <code>casino.casinos</code>
     */
    public static final Casinos CASINOS = new Casinos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CasinosRecord> getRecordType() {
        return CasinosRecord.class;
    }

    /**
     * The column <code>casino.casinos.id</code>.
     */
    public final TableField<CasinosRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>casino.casinos.name</code>.
     */
    public final TableField<CasinosRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>casino.casinos.balance</code>.
     */
    public final TableField<CasinosRecord, Double> BALANCE = createField(DSL.name("balance"), org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "");

    /**
     * Create a <code>casino.casinos</code> table reference
     */
    public Casinos() {
        this(DSL.name("casinos"), null);
    }

    /**
     * Create an aliased <code>casino.casinos</code> table reference
     */
    public Casinos(String alias) {
        this(DSL.name(alias), CASINOS);
    }

    /**
     * Create an aliased <code>casino.casinos</code> table reference
     */
    public Casinos(Name alias) {
        this(alias, CASINOS);
    }

    private Casinos(Name alias, Table<CasinosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Casinos(Name alias, Table<CasinosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Casinos(Table<O> child, ForeignKey<O, CasinosRecord> key) {
        super(child, key, CASINOS);
    }

    @Override
    public Schema getSchema() {
        return Casino.CASINO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CASINOS_ID_UNIQUE, Indexes.CASINOS_PRIMARY);
    }

    @Override
    public Identity<CasinosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CASINOS;
    }

    @Override
    public UniqueKey<CasinosRecord> getPrimaryKey() {
        return Keys.KEY_CASINOS_PRIMARY;
    }

    @Override
    public List<UniqueKey<CasinosRecord>> getKeys() {
        return Arrays.<UniqueKey<CasinosRecord>>asList(Keys.KEY_CASINOS_PRIMARY, Keys.KEY_CASINOS_ID_UNIQUE);
    }

    @Override
    public Casinos as(String alias) {
        return new Casinos(DSL.name(alias), this);
    }

    @Override
    public Casinos as(Name alias) {
        return new Casinos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Casinos rename(String name) {
        return new Casinos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Casinos rename(Name name) {
        return new Casinos(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
