/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db;


import com.casino.jooq.db.tables.Bets;
import com.casino.jooq.db.tables.Casinos;
import com.casino.jooq.db.tables.Dealers;
import com.casino.jooq.db.tables.Games;
import com.casino.jooq.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Casino extends SchemaImpl {

    private static final long serialVersionUID = 109877909;

    /**
     * The reference instance of <code>casino</code>
     */
    public static final Casino CASINO = new Casino();

    /**
     * The table <code>casino.bets</code>.
     */
    public final Bets BETS = com.casino.jooq.db.tables.Bets.BETS;

    /**
     * The table <code>casino.casinos</code>.
     */
    public final Casinos CASINOS = com.casino.jooq.db.tables.Casinos.CASINOS;

    /**
     * The table <code>casino.dealers</code>.
     */
    public final Dealers DEALERS = com.casino.jooq.db.tables.Dealers.DEALERS;

    /**
     * The table <code>casino.games</code>.
     */
    public final Games GAMES = com.casino.jooq.db.tables.Games.GAMES;

    /**
     * The table <code>casino.users</code>.
     */
    public final Users USERS = com.casino.jooq.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Casino() {
        super("casino", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bets.BETS,
            Casinos.CASINOS,
            Dealers.DEALERS,
            Games.GAMES,
            Users.USERS);
    }
}
