/*
 * This file is generated by jOOQ.
 */
package com.casino.jooq.db;


import com.casino.jooq.db.tables.Bets;
import com.casino.jooq.db.tables.Casinos;
import com.casino.jooq.db.tables.Dealers;
import com.casino.jooq.db.tables.Games;
import com.casino.jooq.db.tables.Users;
import com.casino.jooq.db.tables.records.BetsRecord;
import com.casino.jooq.db.tables.records.CasinosRecord;
import com.casino.jooq.db.tables.records.DealersRecord;
import com.casino.jooq.db.tables.records.GamesRecord;
import com.casino.jooq.db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>casino</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BetsRecord, Integer> IDENTITY_BETS = Identities0.IDENTITY_BETS;
    public static final Identity<CasinosRecord, Integer> IDENTITY_CASINOS = Identities0.IDENTITY_CASINOS;
    public static final Identity<DealersRecord, Integer> IDENTITY_DEALERS = Identities0.IDENTITY_DEALERS;
    public static final Identity<GamesRecord, Integer> IDENTITY_GAMES = Identities0.IDENTITY_GAMES;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BetsRecord> KEY_BETS_PRIMARY = UniqueKeys0.KEY_BETS_PRIMARY;
    public static final UniqueKey<BetsRecord> KEY_BETS_ID_UNIQUE = UniqueKeys0.KEY_BETS_ID_UNIQUE;
    public static final UniqueKey<CasinosRecord> KEY_CASINOS_PRIMARY = UniqueKeys0.KEY_CASINOS_PRIMARY;
    public static final UniqueKey<CasinosRecord> KEY_CASINOS_ID_UNIQUE = UniqueKeys0.KEY_CASINOS_ID_UNIQUE;
    public static final UniqueKey<DealersRecord> KEY_DEALERS_PRIMARY = UniqueKeys0.KEY_DEALERS_PRIMARY;
    public static final UniqueKey<DealersRecord> KEY_DEALERS_ID_UNIQUE = UniqueKeys0.KEY_DEALERS_ID_UNIQUE;
    public static final UniqueKey<GamesRecord> KEY_GAMES_PRIMARY = UniqueKeys0.KEY_GAMES_PRIMARY;
    public static final UniqueKey<GamesRecord> KEY_GAMES_ID_UNIQUE = UniqueKeys0.KEY_GAMES_ID_UNIQUE;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_ID_UNIQUE = UniqueKeys0.KEY_USERS_ID_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BetsRecord, UsersRecord> GAME_USER = ForeignKeys0.GAME_USER;
    public static final ForeignKey<BetsRecord, GamesRecord> GAME_BET = ForeignKeys0.GAME_BET;
    public static final ForeignKey<DealersRecord, CasinosRecord> CASINO_DEALER = ForeignKeys0.CASINO_DEALER;
    public static final ForeignKey<GamesRecord, CasinosRecord> CASINO_GAME = ForeignKeys0.CASINO_GAME;
    public static final ForeignKey<GamesRecord, DealersRecord> DEALER_GAME = ForeignKeys0.DEALER_GAME;
    public static final ForeignKey<UsersRecord, CasinosRecord> CASINO_USER = ForeignKeys0.CASINO_USER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BetsRecord, Integer> IDENTITY_BETS = Internal.createIdentity(Bets.BETS, Bets.BETS.ID);
        public static Identity<CasinosRecord, Integer> IDENTITY_CASINOS = Internal.createIdentity(Casinos.CASINOS, Casinos.CASINOS.ID);
        public static Identity<DealersRecord, Integer> IDENTITY_DEALERS = Internal.createIdentity(Dealers.DEALERS, Dealers.DEALERS.ID);
        public static Identity<GamesRecord, Integer> IDENTITY_GAMES = Internal.createIdentity(Games.GAMES, Games.GAMES.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<BetsRecord> KEY_BETS_PRIMARY = Internal.createUniqueKey(Bets.BETS, "KEY_bets_PRIMARY", Bets.BETS.ID);
        public static final UniqueKey<BetsRecord> KEY_BETS_ID_UNIQUE = Internal.createUniqueKey(Bets.BETS, "KEY_bets_id_UNIQUE", Bets.BETS.ID);
        public static final UniqueKey<CasinosRecord> KEY_CASINOS_PRIMARY = Internal.createUniqueKey(Casinos.CASINOS, "KEY_casinos_PRIMARY", Casinos.CASINOS.ID);
        public static final UniqueKey<CasinosRecord> KEY_CASINOS_ID_UNIQUE = Internal.createUniqueKey(Casinos.CASINOS, "KEY_casinos_Id_UNIQUE", Casinos.CASINOS.ID);
        public static final UniqueKey<DealersRecord> KEY_DEALERS_PRIMARY = Internal.createUniqueKey(Dealers.DEALERS, "KEY_dealers_PRIMARY", Dealers.DEALERS.ID);
        public static final UniqueKey<DealersRecord> KEY_DEALERS_ID_UNIQUE = Internal.createUniqueKey(Dealers.DEALERS, "KEY_dealers_id_UNIQUE", Dealers.DEALERS.ID);
        public static final UniqueKey<GamesRecord> KEY_GAMES_PRIMARY = Internal.createUniqueKey(Games.GAMES, "KEY_games_PRIMARY", Games.GAMES.ID);
        public static final UniqueKey<GamesRecord> KEY_GAMES_ID_UNIQUE = Internal.createUniqueKey(Games.GAMES, "KEY_games_id_UNIQUE", Games.GAMES.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_ID_UNIQUE = Internal.createUniqueKey(Users.USERS, "KEY_users_id_UNIQUE", Users.USERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BetsRecord, UsersRecord> GAME_USER = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_USERS_PRIMARY, Bets.BETS, "game-user", Bets.BETS.USERID);
        public static final ForeignKey<BetsRecord, GamesRecord> GAME_BET = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_GAMES_PRIMARY, Bets.BETS, "game-bet", Bets.BETS.GAMEID);
        public static final ForeignKey<DealersRecord, CasinosRecord> CASINO_DEALER = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_CASINOS_PRIMARY, Dealers.DEALERS, "casino-dealer", Dealers.DEALERS.CASINOID);
        public static final ForeignKey<GamesRecord, CasinosRecord> CASINO_GAME = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_CASINOS_PRIMARY, Games.GAMES, "casino-game", Games.GAMES.CASINOID);
        public static final ForeignKey<GamesRecord, DealersRecord> DEALER_GAME = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_DEALERS_PRIMARY, Games.GAMES, "dealer-game", Games.GAMES.DEALERID);
        public static final ForeignKey<UsersRecord, CasinosRecord> CASINO_USER = Internal.createForeignKey(com.casino.jooq.db.Keys.KEY_CASINOS_PRIMARY, Users.USERS, "casino-user", Users.USERS.CASINOID);
    }
}
